#!/usr/bin/env python3
"""Build the user-style synthetic ``.mph`` that the G3 chain C case continues from.

What it produces
----------------
One COMSOL model, built **only** through the published MCP operations of the
production stdio entrypoint (``python -m comsol_mcp.mcp_server``), saved as a
``.mph`` plus a JSON receipt:

* a component/geometry with a block (a *user* geometry, deliberately unrelated
  to the chain A/B acceptance numbers),
* a constant material on the block **and** a second, unused material in the
  tree (non-target node),
* a heat-transfer physics interface with a user boundary condition **and** a
  second heat-transfer interface that is switched off in the study step
  (non-target nodes),
* a mesh (built, with statistics),
* a transient study with the exact tags chain C targets: study ``std1`` and
  step ``time`` (``--study-tag``/``--step-tag`` are validated against those
  requirements, never silently defaulted to something else),
* a solver sequence generated by ``study.solver_generate`` (``createAutoSequences``)
  that is then **edited by hand** through ``solver.feature_update`` so a
  continuation must preserve it rather than regenerate it,
* optionally a Derived Values node, and
* a solution (unless ``--skip-solve``), because a user-style continuation model
  normally carries one.

Every property value is finally typed from the *engine's own* property
metadata: the builder creates a node, reads ``node.property_schema`` for the
property it wants to set, and only then writes it (``*_update``).  Nothing is
guessed; when the engine cannot describe a property the value is skipped and
the reason is recorded in the receipt.

Honest limits (recorded, never synthesised)
-------------------------------------------
* ``--with-derived-value`` is the only route to a Derived Values node: the
  published G3 surface has no derived-value operation.  The builder therefore
  asks the *live* session whether any trusted-code (Java execution) tool is
  published and only then attempts ``tools/java/Phase4ChainCDerivedValue.java``.
  This build publishes none, and when no route exists -- or it is refused or
  fails -- the receipt says ``derived_values.mode = "skipped"`` with the
  observed reason.  No node is ever claimed without an engine readback.
* A failing optional step (solve, manual solver edit, derived value) never
  turns into a PASS anywhere in the receipt.
* This script never starts, stops or otherwise manages COMSOL, and never
  modifies ``tools/phase4_run_mcp.py``; it imports that driver read-only and
  reuses its ``ProductionHost``/``ActionClient``/``_execution`` conventions so
  the fixture and the acceptance driver speak the same wire dialect.

Offline use
-----------
``--help``, ``--dry-run`` (prints the plan, touches no engine and writes no
file) and ``--handshake-only`` (spawns the stdio child, initializes, lists
tools, writes a receipt, calls no model operation) all work without a COMSOL
Server.
"""
from __future__ import annotations

import argparse
import asyncio
from datetime import datetime, timezone
import importlib.util
import json
import os
from pathlib import Path
import sys
import time
from typing import Any, Iterable, Mapping, Sequence

ROOT = Path(__file__).resolve().parents[1]
DRIVER_PATH = ROOT / "tools" / "phase4_run_mcp.py"
DERIVED_VALUE_SOURCE = "tools/java/Phase4ChainCDerivedValue.java"
DERIVED_VALUE_ENTRYPOINT = "Phase4ChainCDerivedValue#run"

#: Substrings the builder looks for when it asks the *live* session whether any
#: trusted-code operation is published.  Nothing is guessed: when no published
#: tool matches, the Derived Values step is recorded as ``skipped``.
TRUSTED_CODE_HINTS = ("execute_java", "code_execute", "execute_code")

#: The chain C case hard-codes these two tags (``_case_w16_t019_chain_c``).  The
#: builder refuses to produce a fixture that the case would silently not find.
REQUIRED_STUDY_TAG = "std1"
REQUIRED_STEP_TAG = "time"

DEFAULT_COMPONENT = "comp1"
DEFAULT_GEOMETRY_TAG = "geom1"
DEFAULT_MESH_TAG = "mesh1"
DEFAULT_PHYSICS_TAG = "ht"
DEFAULT_MATERIAL_TAG = "mat1"
DEFAULT_SECOND_MATERIAL_TAG = "mat2"
DEFAULT_SECOND_PHYSICS_TAG = "ht2"
DEFAULT_BLOCK_TAG = "blk1"
DEFAULT_TEMPERATURE_TAG = "temp1"
DEFAULT_HEAT_FLUX_TAG = "hf1"
DEFAULT_TIME_POINTS = (0.0, 0.5, 1.0, 2.0, 5.0)

#: ``solver.feature_update`` candidates for the *manual* edit that makes the
#: generated sequence count as hand-edited.  The first candidate whose feature
#: type is present in the generated tree is attempted; the property names are
#: the documented tables of the W16 layer (Table 6-70 / Table 6-74) or the
#: engine's own ``properties()`` enumeration.  A candidate that the engine or
#: the operation refuses is recorded and the next one is tried.
DEFAULT_SOLVER_EDITS: tuple[tuple[str, str, Any], ...] = (
    ("Time", "rtol", 1e-5),
    ("Stationary", "stol", 1e-6),
    ("FullyCoupled", "maxiter", 50),
    ("Direct", "linsolver", "pardiso"),
)

#: The ordered build plan.  ``--dry-run`` prints exactly this and the offline
#: tests assert it, so the printed plan and the executed plan cannot drift.
PLAN_STEPS: tuple[dict[str, str], ...] = (
    {"step": "model_create", "operation": "model_create (legacy published route)",
     "why": "fresh MCP-owned model; the strict model.create operation is not implemented in this build"},
    {"step": "component_create", "operation": "definition.component_manage",
     "why": "component comp1"},
    {"step": "geometry_create", "operation": "geometry.sequence_create", "why": "3D geometry geom1"},
    {"step": "geometry_block", "operation": "geometry.feature_create + geometry.feature_update",
     "why": "user block blk1 (size/pos typed from the engine's own property metadata)"},
    {"step": "geometry_build", "operation": "geometry.build", "why": "finalize the geometry sequence"},
    {"step": "material_target", "operation": "material.create + material.set_properties + material.selection_set",
     "why": "constant material mat1 bound to the block domain"},
    {"step": "material_unrelated", "operation": "material.create + material.set_properties",
     "why": "second, unused material mat2 (non-target node that must survive the continuation)"},
    {"step": "physics_create", "operation": "physics.create", "why": "HeatTransfer ht on geom1"},
    {"step": "physics_initial_values", "operation": "physics.feature_update",
     "why": "user initial temperature on the auto-created init1 feature"},
    {"step": "physics_temperature_boundary", "operation": "physics.feature_create + physics.feature_update",
     "why": "user temperature boundary temp1"},
    {"step": "physics_heat_flux", "operation": "physics.feature_create + physics.feature_update",
     "why": "user heat-flux boundary hf1"},
    {"step": "physics_unrelated", "operation": "physics.create",
     "why": "second heat-transfer interface ht2 (non-target node, switched off in the study step)"},
    {"step": "mesh_create", "operation": "mesh.create + mesh.inspect", "why": "mesh sequence mesh1"},
    {"step": "mesh_size", "operation": "mesh.feature_update",
     "why": "user mesh size on the sequence's own Size feature"},
    {"step": "mesh_build", "operation": "mesh.build + mesh.statistics", "why": "built mesh with element counts"},
    {"step": "study_create", "operation": "study.create", "why": "study std1 (required tag)"},
    {"step": "study_step_transient", "operation": "study.step_create",
     "why": "transient step time (required tag)"},
    {"step": "study_step_tlist", "operation": "study.step_update",
     "why": "user time list on std1/time, typed from the engine's property metadata"},
    {"step": "study_physics_activation", "operation": "study.physics_activation",
     "why": "switch the unrelated physics ht2 off inside the transient step"},
    {"step": "study_solver_generate", "operation": "study.solver_generate",
     "why": "attach a generated solver sequence to std1 (createAutoSequences)"},
    {"step": "solver_inspect", "operation": "solver.list + solver.inspect",
     "why": "read the generated solver tree before editing it"},
    {"step": "manual_solver_edit", "operation": "solver.feature_update",
     "why": "hand-edit one solver sub-feature so the sequence is preserved, not regenerated"},
    {"step": "study_run", "operation": "study.run",
     "why": "solve the user study (skipped with --skip-solve)"},
    {"step": "derived_values", "operation": "trusted-code tool (only with --with-derived-value)",
     "why": "user Derived Values node; recorded as skipped when no trusted-code route is published"},
    {"step": "model_save", "operation": "model.save", "why": "write the .mph fixture and hash it"},
    {"step": "verify", "operation": "node.find + node.property_get + study.inspect + solver.list",
     "why": "post-save readback of the required structure (tags, tlist, material/physics inventory)"},
)


class FixtureError(RuntimeError):
    """Driver-side failure that is not a capability block."""


class FixtureBlocked(RuntimeError):
    """The runtime could not carry the fixture (capability/handshake)."""


def _utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def load_driver() -> Any:
    """Import ``tools/phase4_run_mcp.py`` read-only (constants + helpers only)."""
    if not DRIVER_PATH.is_file():
        raise FixtureError(f"the phase4 driver is missing: {DRIVER_PATH}")
    name = "phase4_run_mcp_chain_c_fixture"
    spec = importlib.util.spec_from_file_location(name, DRIVER_PATH)
    if spec is None or spec.loader is None:
        raise FixtureError(f"the phase4 driver could not be loaded: {DRIVER_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    try:
        spec.loader.exec_module(module)
    except ModuleNotFoundError as exc:  # the MCP SDK lives in the driver environment
        raise FixtureError(
            f"{exc.name!r} is required to host the MCP stdio client; run this script with the same "
            f"interpreter that hosts comsol_mcp.mcp_server (--python)"
        ) from exc
    return module


def parse_time_points(text: str) -> list[float]:
    points: list[float] = []
    for item in str(text).replace(";", ",").split(","):
        item = item.strip()
        if not item:
            continue
        try:
            value = float(item)
        except ValueError:
            raise argparse.ArgumentTypeError(f"time point {item!r} is not a number")
        if value < 0.0:
            raise argparse.ArgumentTypeError(f"time point {item!r} is negative")
        points.append(value)
    if not points:
        raise argparse.ArgumentTypeError("at least one time point is required")
    if len(points) < 2:
        raise argparse.ArgumentTypeError("at least two time points are required for a transient list")
    if any(later <= earlier for earlier, later in zip(points, points[1:])):
        raise argparse.ArgumentTypeError("time points must be strictly increasing")
    return points


def parse_solver_edit(text: str) -> tuple[str, str, Any]:
    if ":" not in text or "=" not in text:
        raise argparse.ArgumentTypeError("expected TYPE:PROPERTY=VALUE (for example Time:rtol=1e-5)")
    head, raw = text.split("=", 1)
    feature_type, property_name = head.split(":", 1)
    feature_type, property_name = feature_type.strip(), property_name.strip()
    if not feature_type or not property_name:
        raise argparse.ArgumentTypeError("expected TYPE:PROPERTY=VALUE (for example Time:rtol=1e-5)")
    value: Any = raw.strip()
    if value.lower() in {"true", "false"}:
        value = value.lower() == "true"
    else:
        try:
            value = int(value)
        except ValueError:
            try:
                value = float(value)
            except ValueError:
                pass
    return feature_type, property_name, value


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="phase4_chain_c_fixture.py",
        description=("Chain C fixture builder: a user-style synthetic model with study std1 / transient step "
                     "time, built through the published MCP operations and saved as a .mph for "
                     "tools/phase4_run_mcp.py --chain-c-model."),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--python", default=sys.executable,
                        help="interpreter that hosts comsol_mcp.mcp_server")
    parser.add_argument("--live", action="store_true",
                        help="build the fixture against the already running COMSOL Server")
    parser.add_argument("--dry-run", action="store_true", help="print the build plan and exit (no engine, no files)")
    parser.add_argument("--handshake-only", action="store_true",
                        help="spawn the stdio child, initialize, list tools, write a receipt, then stop")
    parser.add_argument("--host", default=os.environ.get("COMSOL_SERVER_HOST", "127.0.0.1"))
    parser.add_argument("--port", type=int, default=int(os.environ.get("COMSOL_SERVER_PORT", "2036")))
    parser.add_argument("--comsol-root", default=os.environ.get("COMSOL_ROOT"),
                        help="COMSOL installation root passed to the server child")
    parser.add_argument("--runtime-root", dest="comsol_root", help="alias of --comsol-root")
    parser.add_argument("--jdk11", default=os.environ.get("COMSOL_JAVA_HOME") or os.environ.get("JAVA_HOME"))
    parser.add_argument("--prefs", default=os.environ.get("COMSOL_PREFS_DIR"))
    parser.add_argument("--private-home", default=None,
                        help="bind an existing private MCP home (default: a fresh fixture-owned home)")
    parser.add_argument("--tool-profile", default=os.environ.get("COMSOL_MCP_TOOL_PROFILE", "full"))
    parser.add_argument("--project-id", default="comsol-mcp-chain-c-fixture")
    parser.add_argument("--run-dir", default=None, help="evidence directory (default: evidence/phase4/chain_c_fixture/<stamp>)")
    parser.add_argument("--output", type=Path, default=None,
                        help=".mph to write (default: <run-dir>/chain_c_user_style.mph)")
    parser.add_argument("--label", default="G3 chain C user-style continuation model")
    parser.add_argument("--component", default=DEFAULT_COMPONENT)
    parser.add_argument("--geometry-tag", default=DEFAULT_GEOMETRY_TAG)
    parser.add_argument("--mesh-tag", default=DEFAULT_MESH_TAG)
    parser.add_argument("--physics-tag", default=DEFAULT_PHYSICS_TAG)
    parser.add_argument("--second-physics-tag", default=DEFAULT_SECOND_PHYSICS_TAG)
    parser.add_argument("--material-tag", default=DEFAULT_MATERIAL_TAG)
    parser.add_argument("--second-material-tag", default=DEFAULT_SECOND_MATERIAL_TAG)
    parser.add_argument("--study-tag", default=REQUIRED_STUDY_TAG,
                        help=f"study tag of the continuation target (chain C requires {REQUIRED_STUDY_TAG!r})")
    parser.add_argument("--step-tag", default=REQUIRED_STEP_TAG,
                        help=f"transient step tag of the continuation target (chain C requires {REQUIRED_STEP_TAG!r})")
    parser.add_argument("--time-points", default=",".join(str(item) for item in DEFAULT_TIME_POINTS),
                        type=parse_time_points, help="transient tlist in seconds, comma separated")
    parser.add_argument("--length", type=float, default=0.03, help="block size in metres")
    parser.add_argument("--width", type=float, default=0.02)
    parser.add_argument("--height", type=float, default=0.01)
    parser.add_argument("--mesh-size-level", type=int, default=4, help="hauto level for the block (1 coarse .. 9 finer)")
    parser.add_argument("--initial-temperature", type=float, default=293.15, help="init1 T0 in kelvin")
    parser.add_argument("--boundary-temperature", type=float, default=353.15, help="temp1 T0 in kelvin")
    parser.add_argument("--material-k", default="0.45[W/(m*K)]")
    parser.add_argument("--material-rho", default="2200[kg/m^3]")
    parser.add_argument("--material-cp", default="880[J/(kg*K)]")
    parser.add_argument("--solve-timeout-s", type=float, default=900.0)
    parser.add_argument("--skip-solve", action="store_true", help="do not run the study while building the fixture")
    parser.add_argument("--with-derived-value", action="store_true",
                        help="attempt a Derived Values node when the session publishes a "
                             "trusted-code (Java execution) tool; otherwise recorded as skipped")
    parser.add_argument("--solver-edit", action="append", type=parse_solver_edit, default=None,
                        metavar="TYPE:PROPERTY=VALUE",
                        help="manual solver edit candidate (repeatable; default: the built-in candidate list)")
    parser.add_argument("--allow-no-manual-solver", action="store_true",
                        help="do not fail the fixture when no manual solver edit could be applied")
    return parser


def validate(args: argparse.Namespace, parser: argparse.ArgumentParser) -> None:
    """Refuse a fixture the chain C case could not use (fail closed, before any engine call)."""
    if args.study_tag != REQUIRED_STUDY_TAG:
        parser.error(f"--study-tag must be {REQUIRED_STUDY_TAG!r}: the chain C case targets that study")
    if args.step_tag != REQUIRED_STEP_TAG:
        parser.error(f"--step-tag must be {REQUIRED_STEP_TAG!r}: the chain C case targets that step")
    for tag, label in ((args.component, "--component"), (args.geometry_tag, "--geometry-tag"),
                       (args.mesh_tag, "--mesh-tag"), (args.physics_tag, "--physics-tag"),
                       (args.second_physics_tag, "--second-physics-tag"), (args.material_tag, "--material-tag"),
                       (args.second_material_tag, "--second-material-tag")):
        if not tag or not tag.replace("_", "").isalnum():
            parser.error(f"{label} must be a plain COMSOL tag")
    if args.component == args.geometry_tag:
        parser.error("--component and --geometry-tag must differ")
    if args.material_tag == args.second_material_tag:
        parser.error("--material-tag and --second-material-tag must differ")
    if args.physics_tag == args.second_physics_tag:
        parser.error("--physics-tag and --second-physics-tag must differ")
    if args.length <= 0 or args.width <= 0 or args.height <= 0:
        parser.error("--length/--width/--height must be positive")
    if not 1 <= args.mesh_size_level <= 9:
        parser.error("--mesh-size-level must be between 1 and 9")
    if args.solve_timeout_s <= 0:
        parser.error("--solve-timeout-s must be positive")
    if not 1 <= args.port <= 65535:
        parser.error("--port must be between 1 and 65535")
    if args.handshake_only and (args.live or args.dry_run):
        parser.error("--handshake-only cannot be combined with --live or --dry-run")
    if not args.live and not args.dry_run and not args.handshake_only:
        parser.error("pass --live to build the fixture, --dry-run to print the plan, or --handshake-only")


def print_plan(args: argparse.Namespace) -> None:
    print("phase4 chain C fixture plan (no engine is contacted)")
    print(f"  study {args.study_tag!r} / transient step {args.step_tag!r} / tlist {list(args.time_points)} s")
    print(f"  step type: Transient (study.step_create type_id), physics {args.physics_tag!r} "
          f"+ unrelated {args.second_physics_tag!r}")
    print(f"  mesh: {args.mesh_tag!r} hauto {args.mesh_size_level}, geometry {args.geometry_tag!r} "
          f"block {args.length}x{args.width}x{args.height} m")
    print(f"  materials: {args.material_tag!r} (k={args.material_k}, rho={args.material_rho}, "
          f"cp={args.material_cp}) + unrelated {args.second_material_tag!r}")
    for index, item in enumerate(PLAN_STEPS, start=1):
        print(f"  {index:>2}. {item['step']:<28} {item['operation']}")
        print(f"      why: {item['why']}")
    derived = ("a Derived Values node is attempted when the live session publishes a trusted-code "
               "tool; otherwise the receipt records skipped" if args.with_derived_value else
               "not requested: --with-derived-value was not passed, so the receipt records skipped")
    print(f"  derived values: {derived}")
    print(f"  manual solver edits: {args.solver_edit or list(DEFAULT_SOLVER_EDITS)}")
    print(f"  solve: {'skipped (--skip-solve)' if args.skip_solve else f'study.run, timeout {args.solve_timeout_s:g}s'}")


class ChainCFixture:
    """One stdio session, one build plan, one receipt."""

    def __init__(self, args: argparse.Namespace, driver: Any, driver_args: argparse.Namespace) -> None:
        self.args = args
        self.driver = driver
        self.driver_args = driver_args
        self.run_dir = Path(args.run_dir).expanduser()
        self.output = Path(args.output).expanduser() if args.output else self.run_dir / "chain_c_user_style.mph"
        self.receipt_path = self.run_dir / "chain_c_fixture_receipt.json"
        self.transcript: list[dict[str, Any]] = []
        self.state: dict[str, Any] = {"ref": None, "revision": None, "model_label": None}
        self.steps: list[dict[str, Any]] = []
        self.warnings: list[str] = []
        self.environment: dict[str, Any] = {}
        self.host: Any = None
        self.client: Any = None
        self.solver_edit: dict[str, Any] = {"attempted": False, "applied": False, "candidates": []}
        self.derived_values: dict[str, Any] = {"mode": "skipped", "reason": "--with-derived-value was not passed"}
        self.tlist: dict[str, Any] = {}
        self.verification: dict[str, Any] = {}

    # -- bookkeeping ------------------------------------------------------

    def record(self, step: str, operation: str, payload: Mapping[str, Any] | None,
               *, status: str | None = None, notes: str | None = None,
               extra: Mapping[str, Any] | None = None) -> dict[str, Any]:
        driver = self.driver
        row: dict[str, Any] = {
            "step": step,
            "operation": operation,
            "success": bool(driver._success(payload)) if payload is not None else False,
            "error_code": driver._error_code(payload) if payload is not None else None,
            "status": status or ("APPLIED" if payload is not None and driver._success(payload) else "FAILED"),
            "outer_isError": payload.get("_outer_isError") if isinstance(payload, Mapping) else None,
            "notes": notes,
        }
        if extra:
            row.update(extra)
        self.steps.append(driver._json_safe(row))
        marker = "ok " if row["success"] or row["status"] in {"APPLIED", "SKIPPED", "INFO"} else "!! "
        detail = row["error_code"] or row["status"]
        print(f"  {marker}{step:<28} {operation:<48} {detail}")
        if row["notes"]:
            print(f"      {row['notes']}")
        return row

    def warn(self, message: str) -> None:
        self.warnings.append(message)
        print(f"  ~~ warning: {message}")

    # -- small helpers ----------------------------------------------------

    def path(self, *segments: Sequence[str]) -> dict[str, Any]:
        return {"segments": [{"collection": collection, "tag": tag} for collection, tag in segments]}

    @property
    def component_path(self) -> dict[str, Any]:
        return self.path(("component", self.args.component))

    @property
    def geometry_path(self) -> dict[str, Any]:
        return self.path(("component", self.args.component), ("geom", self.args.geometry_tag))

    @property
    def mesh_path(self) -> dict[str, Any]:
        return self.path(("component", self.args.component), ("mesh", self.args.mesh_tag))

    @property
    def physics_path(self) -> dict[str, Any]:
        return self.path(("component", self.args.component), ("physics", self.args.physics_tag))

    @property
    def study_path(self) -> dict[str, Any]:
        return self.path(("study", self.args.study_tag))

    @property
    def study_step_path(self) -> dict[str, Any]:
        return self.path(("study", self.args.study_tag), ("feature", self.args.step_tag))

    @property
    def material_path(self) -> dict[str, Any]:
        return self.path(("component", self.args.component), ("material", self.args.material_tag))

    async def action(self, operation: str, body: Mapping[str, Any] | None = None, *, key: str) -> dict[str, Any]:
        assert self.client is not None
        try:
            return await self.client.action(operation, dict(body or {}), key=key, request=key)
        except self.driver.CapabilityUnavailable as exc:
            print(f"  !! {operation:<48} capability unavailable: {exc}")
            return self.driver._synthetic_blocked(operation, str(exc))

    async def read_schema(self, path: Mapping[str, Any], names: Iterable[str], *, key: str) -> dict[str, Any]:
        """Read the engine's own property metadata for the requested names."""
        payload = await self.action("node.property_schema", {"path": dict(path)}, key=key)
        rows = [dict(row) for row in self.driver._data(payload).get("properties", [])
                if isinstance(row, Mapping) and isinstance(row.get("name"), str)]
        wanted = {str(name) for name in names}
        return {row["name"]: row for row in rows if not wanted or row["name"] in wanted}

    def coerce(self, value: Any, row: Mapping[str, Any], label: str) -> tuple[Any, str | None]:
        """Return ``(raw wire value, refusal)`` from the engine's own metadata.

        The G3 write operations take the *raw* value and type it from the target
        node's metadata themselves.  ``int64`` is deliberately refused: the
        published layer has no verified int64 setter, so guessing one here would
        move an unverified conversion into the fixture.
        """
        kind, rank = row.get("kind"), row.get("shape_rank")
        if row.get("metadata_status") != "KNOWN" or kind is None or rank is None:
            return None, f"{label}: the engine reported no value metadata (metadata_status={row.get('metadata_status')!r})"
        if kind == "int64":
            return None, f"{label}: value kind int64 has no verified setter in the published layer"

        def scalar(item: Any) -> Any:
            if kind == "boolean":
                if isinstance(item, bool):
                    return item
                return str(item).strip().lower() in {"on", "true", "1"}
            if kind == "int32":
                return int(item)
            if kind == "float64":
                return float(item)
            if kind in {"string", "expression"}:
                return item if isinstance(item, str) else json.dumps(item) if isinstance(item, (list, dict)) else str(item)
            raise ValueError(f"unsupported kind {kind!r}")

        try:
            if rank == 0:
                return scalar(value), None
            if rank == 1:
                items = list(value) if isinstance(value, (list, tuple)) else [value]
                return [scalar(item) for item in items], None
            rows = list(value) if isinstance(value, (list, tuple)) else [value]
            return [[scalar(item) for item in (list(row) if isinstance(row, (list, tuple)) else [row])]
                    for row in rows], None
        except (TypeError, ValueError) as exc:
            return None, f"{label}: value {value!r} does not fit the engine's {kind!r} (rank {rank}) metadata ({exc})"

    async def set_properties(self, step: str, operation: str, path: Mapping[str, Any],
                             wanted: Mapping[str, Any], *, key: str, notes: str | None = None,
                             extra: Mapping[str, Any] | None = None) -> dict[str, Any]:
        """Write properties through the engine's metadata: read the schema, then update.

        ``extra`` carries operation-specific arguments the published contract requires
        in addition to ``path``/``properties`` (``material.set_properties`` needs its
        property ``group``, for example).
        """
        schema = await self.read_schema(path, wanted.keys(), key=key + "-schema")
        if not schema:
            return self.record(step, f"{operation} (property write)", None, status="SKIPPED",
                               notes=f"{notes or ''} the engine returned no property metadata for {sorted(wanted)}".strip())
        values: dict[str, Any] = {}
        refusals: list[str] = []
        detail: dict[str, Any] = {}
        for name, value in wanted.items():
            row = schema.get(name)
            if row is None:
                refusals.append(f"{name}: the target node does not expose this property")
                continue
            coerced, refusal = self.coerce(value, row, name)
            if refusal:
                refusals.append(refusal)
                continue
            values[name] = coerced
            detail[name] = {"requested": coerced, "engine_kind": row.get("kind"),
                            "engine_shape_rank": row.get("shape_rank"),
                            "engine_value_type": row.get("value_type")}
        if not values:
            return self.record(step, f"{operation} (property write)", None, status="SKIPPED",
                               notes="; ".join(refusals) or "no writable property was found")
        body: dict[str, Any] = {"path": dict(path), "properties": values, **dict(extra or {})}
        payload = await self.action(operation, body, key=key)
        notes_all = "; ".join([refusals[0]] if refusals else []) if refusals else notes
        return self.record(step, operation, payload, notes=notes_all, extra={"written": detail,
                                                                            "refused": refusals,
                                                                            "request_arguments": sorted(body)})

    # -- build ------------------------------------------------------------

    async def build(self, host: Any, client: Any) -> int:
        self.host, self.client = host, client
        args, driver = self.args, self.driver

        connect = await host.call("server_connect", {
            "host": args.host, "port": args.port,
            "execution": driver._execution(key="fixture-connect", request="fixture-connect"),
        })
        if not driver._success(connect):
            reason = f"server_connect failed: {driver._error_code(connect) or 'UNKNOWN'}"
            self.record("server_connect", "server_connect", connect, status="BLOCKED", notes=reason)
            raise FixtureBlocked(reason)
        self.record("server_connect", "server_connect", connect,
                    notes="engine connection established before the build steps")

        created = await driver._create_empty_model(client, self.state, args.label, host)
        ref = self.state.get("ref") if isinstance(self.state.get("ref"), Mapping) else None
        self.record("model_create", "model_create", created,
                    notes="legacy published route: the strict model.create operation is not implemented",
                    extra={"execution": driver._json_safe(driver._envelope_identity(created)),
                           "model_ref": driver._json_safe(ref)})
        if not (driver._success(created) and isinstance(self.state.get("ref"), Mapping)):
            reason = (f"model_create returned {driver._error_code(created) or 'an invalid envelope'}; "
                      "no model_ref was bound")
            self.record("model_create", "model_create", created, status="BLOCKED", notes=reason)
            raise FixtureBlocked(reason)
        print(f"  .. bound model_ref: {self.state.get('ref')}")

        # 1. component + geometry -------------------------------------------------
        payload = await self.action("definition.component_manage",
                                    {"action": "create", "tag": args.component}, key="fixture-component")
        self.record("component_create", "definition.component_manage", payload)
        if not driver._success(payload):
            raise FixtureBlocked(f"component {args.component!r} could not be created: {driver._error_code(payload)}")

        payload = await self.action("geometry.sequence_create",
                                    {"component": args.component, "tag": args.geometry_tag, "dimension": 3},
                                    key="fixture-geometry")
        self.record("geometry_create", "geometry.sequence_create", payload)
        if not driver._success(payload):
            raise FixtureBlocked(f"geometry {args.geometry_tag!r} could not be created: {driver._error_code(payload)}")

        payload = await self.action("geometry.feature_create",
                                    {"parent": self.geometry_path, "tag": DEFAULT_BLOCK_TAG,
                                     "type_id": "Block", "properties": {}},
                                    key="fixture-block")
        block_created = driver._success(payload)
        self.record("geometry_block", "geometry.feature_create", payload,
                    notes=None if block_created else
                    "the block feature was not created; geometry.size/pos are skipped")
        if block_created:
            block_path = self.path(("component", args.component), ("geom", args.geometry_tag),
                                   ("feature", DEFAULT_BLOCK_TAG))
            await self.set_properties(
                "geometry_block", "geometry.feature_update", block_path,
                {"size": [args.length, args.width, args.height], "pos": [0.0, 0.0, 0.0]},
                key="fixture-block-props",
                notes="size/pos typed from the Block node's own property metadata")

        payload = await self.action("geometry.build", {"geometry": self.geometry_path}, key="fixture-geometry-build")
        self.record("geometry_build", "geometry.build", payload)
        if not driver._success(payload):
            raise FixtureBlocked(f"the geometry could not be built: {driver._error_code(payload)}")

        # 2. materials (target + an unrelated, unused one) ------------------------
        payload = await self.action("material.create",
                                    {"component": args.component, "tag": args.material_tag, "type_id": "Common"},
                                    key="fixture-material")
        self.record("material_target", "material.create", payload)
        if not driver._success(payload):
            raise FixtureBlocked(f"material {args.material_tag!r} could not be created: {driver._error_code(payload)}")
        await self.set_properties("material_target", "material.set_properties", self.material_path,
                                  {"thermalconductivity": [[args.material_k, "0", "0"],
                                                           ["0", args.material_k, "0"],
                                                           ["0", "0", args.material_k]],
                                   "density": args.material_rho, "heatcapacity": args.material_cp},
                                  key="fixture-material-props", extra={"group": "def"},
                                  notes="group 'def'; expression text is written verbatim")
        payload = await self.action("material.selection_set", {
            "path": self.material_path,
            "selection": {"kind": "explicit", "component": args.component, "geometry": args.geometry_tag,
                          "entity_dimension": 3, "entities": [1]}}, key="fixture-material-selection")
        self.record("material_target", "material.selection_set", payload,
                    notes="explicit domain binding: domain 1")

        payload = await self.action("material.create",
                                    {"component": args.component, "tag": args.second_material_tag, "type_id": "Common"},
                                    key="fixture-material-2")
        second_material_ok = driver._success(payload)
        self.record("material_unrelated", "material.create", payload,
                    notes=None if second_material_ok else "the unrelated second material could not be created")
        if second_material_ok:
            second_path = self.path(("component", args.component), ("material", args.second_material_tag))
            await self.set_properties("material_unrelated", "material.set_properties", second_path,
                                      {"thermalconductivity": [["1[W/(m*K)]", "0", "0"],
                                                               ["0", "1[W/(m*K)]", "0"],
                                                               ["0", "0", "1[W/(m*K)]"]],
                                       "density": "1000[kg/m^3]", "heatcapacity": "1000[J/(kg*K)]"},
                                      key="fixture-material-2-props", extra={"group": "def"},
                                      notes="deliberately unused material: a non-target node that must survive")

        # 3. physics --------------------------------------------------------------
        payload = await self.action("physics.create",
                                    {"component": args.component, "tag": args.physics_tag,
                                     "type_id": "HeatTransfer", "geometry": args.geometry_tag},
                                    key="fixture-physics")
        self.record("physics_create", "physics.create", payload)
        if not driver._success(payload):
            raise FixtureBlocked(f"physics {args.physics_tag!r} could not be created: {driver._error_code(payload)}")

        inspected = await self.action("physics.inspect", {"path": self.physics_path, "depth": 2},
                                      key="fixture-physics-inspect")
        feature_rows = self.collect_tree(driver._data(inspected))
        initial_candidates = [str(row.get("tag")) for row in feature_rows
                              if row.get("tag") and ("init" in str(row.get("tag")).lower()
                                                     or "init" in str(row.get("type_id") or "").lower())]
        if not initial_candidates:
            initial_candidates = ["init1"]
        initial_written = None
        for initial_tag in initial_candidates:
            initial_path = self.path(("component", args.component), ("physics", args.physics_tag),
                                     ("feature", initial_tag))
            outcome = await self.set_properties("physics_initial_values", "physics.feature_update", initial_path,
                                                {"T0": args.initial_temperature},
                                                key=f"fixture-init-t0-{initial_tag}",
                                                notes=f"user initial temperature on feature {initial_tag!r}")
            if outcome["success"]:
                initial_written = initial_tag
                break
        if initial_written is None:
            self.warn("the initial-values feature could not be identified/written; see physics_initial_values")

        payload = await self.action("physics.feature_create",
                                    {"parent": self.physics_path, "tag": DEFAULT_TEMPERATURE_TAG,
                                     "type_id": "TemperatureBoundary", "entity_dimension": 2},
                                    key="fixture-temp-boundary")
        temperature_ok = driver._success(payload)
        self.record("physics_temperature_boundary", "physics.feature_create", payload,
                    notes="verified heat-transfer boundary token TemperatureBoundary")
        if temperature_ok:
            await self.set_properties(
                "physics_temperature_boundary", "physics.feature_update",
                self.path(("component", args.component), ("physics", args.physics_tag),
                          ("feature", DEFAULT_TEMPERATURE_TAG)),
                {"T0": args.boundary_temperature}, key="fixture-temp-t0",
                notes="user boundary temperature")

        payload = await self.action("physics.feature_create",
                                    {"parent": self.physics_path, "tag": DEFAULT_HEAT_FLUX_TAG,
                                     "type_id": "HeatFluxBoundary", "entity_dimension": 2},
                                    key="fixture-heat-flux")
        self.record("physics_heat_flux", "physics.feature_create", payload,
                    notes="second user boundary condition (non-target node)")

        payload = await self.action("physics.create",
                                    {"component": args.component, "tag": args.second_physics_tag,
                                     "type_id": "HeatTransfer", "geometry": args.geometry_tag},
                                    key="fixture-physics-2")
        self.record("physics_unrelated", "physics.create", payload,
                    notes="unrelated interface: switched off inside the study step, and must survive the continuation")

        # 4. mesh -----------------------------------------------------------------
        payload = await self.action("mesh.create",
                                    {"component": args.component, "tag": args.mesh_tag,
                                     "geometry": args.geometry_tag}, key="fixture-mesh")
        self.record("mesh_create", "mesh.create", payload)
        if not driver._success(payload):
            raise FixtureBlocked(f"mesh {args.mesh_tag!r} could not be created: {driver._error_code(payload)}")

        inspected = await self.action("mesh.inspect", {"path": self.mesh_path, "depth": 2},
                                      key="fixture-mesh-inspect")
        features = self.collect_tree(driver._data(inspected))
        self.record("mesh_create", "mesh.inspect", inspected,
                    extra={"features": [{"tag": row.get("tag"), "type_id": row.get("type_id")} for row in features]})
        size_row = next((row for row in features if row.get("type_id") == "Size"), None)
        if size_row is None or not size_row.get("tag"):
            self.warn("the mesh sequence exposes no Size feature; --mesh-size-level was not applied")
            self.record("mesh_size", "mesh.feature_update", None, status="SKIPPED",
                        notes="no Size feature was found in the mesh sequence")
        else:
            size_path = self.path(("component", args.component), ("mesh", args.mesh_tag),
                                  ("feature", str(size_row.get("tag"))))
            await self.set_properties("mesh_size", "mesh.feature_update", size_path,
                                      {"hauto": args.mesh_size_level}, key="fixture-mesh-size",
                                      notes=f"user mesh size (hauto={args.mesh_size_level})")

        payload = await self.action("mesh.build", {"path": self.mesh_path}, key="fixture-mesh-build")
        self.record("mesh_build", "mesh.build", payload)
        if not driver._success(payload):
            raise FixtureBlocked(f"the mesh could not be built: {driver._error_code(payload)}")
        statistics = await self.action("mesh.statistics", {"path": self.mesh_path}, key="fixture-mesh-statistics")
        self.record("mesh_build", "mesh.statistics", statistics,
                    extra={"statistics": driver._json_safe(driver._data(statistics))})

        # 5. study std1 + transient step time -------------------------------------
        payload = await self.action("study.create", {"tag": args.study_tag, "label": args.label},
                                    key="fixture-study")
        self.record("study_create", "study.create", payload)
        if not driver._success(payload):
            raise FixtureBlocked(f"study {args.study_tag!r} could not be created: {driver._error_code(payload)}")

        payload = await self.action("study.step_create",
                                    {"study": self.study_path, "tag": args.step_tag, "type_id": "Transient",
                                     "properties": {}}, key="fixture-study-step")
        self.record("study_step_transient", "study.step_create", payload,
                    notes="documented create string for Time Dependent is 'Transient'")
        if not driver._success(payload):
            raise FixtureBlocked(f"transient step {args.step_tag!r} could not be created: {driver._error_code(payload)}")

        tlist = await self.set_properties("study_step_tlist", "study.step_update", self.study_step_path,
                                          {"tlist": list(args.time_points)}, key="fixture-tlist",
                                          notes="user time list, typed from the step's own property metadata")
        schema = await self.read_schema(self.study_step_path, ("tlist",), key="fixture-tlist-schema")
        self.tlist = {"requested": list(args.time_points), "engine_metadata": driver._json_safe(schema.get("tlist")),
                      "write": tlist}

        activation = await self.action("study.physics_activation", {
            "step": self.study_step_path,
            "activation": {"physics": {args.second_physics_tag: False}}}, key="fixture-activation")
        self.record("study_physics_activation", "study.physics_activation", activation,
                    notes=f"the unrelated interface {args.second_physics_tag!r} is switched off in the transient step")

        generated = await self.action("study.solver_generate",
                                      {"study": self.study_path, "replace_existing": False},
                                      key="fixture-solver-generate")
        self.record("study_solver_generate", "study.solver_generate", generated,
                    notes="createAutoSequences('sol'): the sequence must be preserved, not regenerated",
                    extra={"created": driver._json_safe(driver._data(generated).get("created"))})

        # 6. read the solver tree, then edit one sub-feature by hand ---------------
        listed = await self.action("solver.list", {"filter": {"study": args.study_tag}}, key="fixture-solver-list")
        solvers = [dict(row) for row in driver._data(listed).get("solvers", []) if isinstance(row, Mapping)]
        self.record("solver_inspect", "solver.list", listed,
                    extra={"solvers": [{"solver": row.get("solver"), "study": row.get("study"),
                                        "feature_count": row.get("feature_count")} for row in solvers]})
        solver_tag = next((str(row.get("solver")) for row in solvers if row.get("solver")), None)
        inspected = None
        solver_features: list[dict[str, Any]] = []
        if solver_tag:
            inspected = await self.action("solver.inspect",
                                          {"path": self.path(("sol", solver_tag)), "depth": 4},
                                          key="fixture-solver-inspect")
            solver_features = self.collect_solver_features(driver._data(inspected))
            self.record("solver_inspect", "solver.inspect", inspected,
                        extra={"solver": solver_tag,
                               "features": [{"tag": row.get("tag"), "type_id": row.get("type_id")}
                                            for row in solver_features]})
        else:
            self.warn("no solver sequence is attached to the study; the manual solver edit is skipped")
            self.record("solver_inspect", "solver.inspect", None, status="SKIPPED",
                        notes="no solver sequence is attached to the study")

        await self.apply_manual_solver_edit(solver_tag, solver_features)

        # 7. solve (a user-style model normally carries a solution) ---------------
        if args.skip_solve:
            self.record("study_run", "study.run", None, status="SKIPPED", notes="--skip-solve was passed")
        else:
            solved = await self.action("study.run",
                                       {"study": self.study_path, "timeout_s": args.solve_timeout_s},
                                       key="fixture-solve")
            self.record("study_run", "study.run", solved,
                        extra={"computation": driver._json_safe(driver._data(solved).get("computation_after"))})
            if not driver._success(solved):
                self.warn(f"the fixture study did not solve ({driver._error_code(solved)}); "
                          "the model is still saved and hashed")

        # 8. derived values -------------------------------------------------------
        await self.attempt_derived_values()

        # 9. save + verify --------------------------------------------------------
        saved = await self.action("model.save",
                                  {"destination": {"path": str(self.output)}, "overwrite": True,
                                   "include_solution": True}, key="fixture-save")
        digest = driver._sha256(self.output) if self.output.is_file() else None
        self.record("model_save", "model.save", saved, extra={"path": str(self.output), "sha256": digest,
                                                             "bytes": self.output.stat().st_size
                                                             if self.output.is_file() else None})
        await self.verify()
        return self.status()

    def collect_tree(self, data: Mapping[str, Any]) -> list[dict[str, Any]]:
        """Flatten the ``features``/``children``/``steps`` trees the G3 read operations return."""
        rows: list[dict[str, Any]] = []

        def walk(item: Any) -> None:
            if not isinstance(item, Mapping):
                return
            if item.get("tag"):
                rows.append(dict(item))
            for child in item.get("children", []) if isinstance(item.get("children"), list) else []:
                walk(child)

        for key in ("features", "children", "steps"):
            value = data.get(key)
            if isinstance(value, list):
                for item in value:
                    walk(item)
        return rows

    def collect_solver_features(self, data: Mapping[str, Any]) -> list[dict[str, Any]]:
        """Flatten the node tree returned by ``solver.inspect`` (depth 4)."""
        return self.collect_tree(data)

    async def apply_manual_solver_edit(self, solver_tag: str | None, features: Sequence[Mapping[str, Any]]) -> None:
        driver, args = self.driver, self.args
        candidates: list[tuple[str, str, Any]] = list(args.solver_edit or DEFAULT_SOLVER_EDITS)
        self.solver_edit = {"attempted": True, "applied": False, "solver": solver_tag,
                            "candidates": [{"feature_type": row[0], "property": row[1], "value": row[2]}
                                           for row in candidates],
                            "observed_features": [{"tag": row.get("tag"), "type_id": row.get("type_id")}
                                                  for row in features],
                            "attempts": []}
        if not solver_tag:
            self.solver_edit["reason"] = "no solver sequence is attached to the study"
            self.record("manual_solver_edit", "solver.feature_update", None, status="SKIPPED",
                        notes=self.solver_edit["reason"])
            return
        for feature_type, property_name, value in candidates:
            row = next((item for item in features if item.get("type_id") == feature_type and item.get("tag")), None)
            if row is None:
                self.solver_edit["attempts"].append({"feature_type": feature_type, "property": property_name,
                                                     "status": "FEATURE_NOT_PRESENT"})
                continue
            path = self.path(("sol", solver_tag), ("feature", str(row.get("tag"))))
            schema = await self.read_schema(path, (property_name,), key=f"fixture-solver-schema-{feature_type}")
            metadata = schema.get(property_name)
            if metadata is None:
                self.solver_edit["attempts"].append({"feature_type": feature_type, "tag": row.get("tag"),
                                                     "property": property_name, "status": "PROPERTY_NOT_EXPOSED"})
                continue
            coerced, refusal = self.coerce(value, metadata, property_name)
            if refusal:
                self.solver_edit["attempts"].append({"feature_type": feature_type, "tag": row.get("tag"),
                                                     "property": property_name, "status": "NOT_WRITABLE",
                                                     "reason": refusal})
                continue
            payload = await self.action("solver.feature_update",
                                        {"path": path, "properties": {property_name: coerced}},
                                        key=f"fixture-solver-edit-{feature_type}")
            driver_data = driver._data(payload)
            status = str(driver_data.get("status") or ("APPLIED" if driver._success(payload) else "FAILED"))
            attempt = {"feature_type": feature_type, "tag": row.get("tag"), "path": path,
                       "property": property_name, "requested": coerced, "engine_metadata": driver._json_safe(metadata),
                       "status": status, "error_code": driver._error_code(payload)}
            self.solver_edit["attempts"].append(attempt)
            if driver._success(payload) and status == "APPLIED":
                readback = await self.action("node.property_get", {"path": path, "names": [property_name]},
                                             key=f"fixture-solver-readback-{feature_type}")
                attempt["readback"] = driver._json_safe(driver._data(readback))
                self.solver_edit.update({"applied": True, "feature_type": feature_type, "tag": row.get("tag"),
                                         "path": path, "property": property_name, "value": coerced})
                self.record("manual_solver_edit", "solver.feature_update", payload,
                            notes=f"hand-edited {feature_type} feature {row.get('tag')!r}: {property_name}={coerced!r}",
                            extra={"path": path, "property": property_name, "value": coerced,
                                   "readback": attempt.get("readback")})
                return
            self.record("manual_solver_edit", "solver.feature_update", payload,
                        notes=f"candidate {feature_type}.{property_name} was refused; trying the next candidate",
                        extra={"path": path})
        self.solver_edit["reason"] = "no candidate solver property could be written"
        self.record("manual_solver_edit", "solver.feature_update", None,
                    status="FAILED" if not args.allow_no_manual_solver else "SKIPPED",
                    notes="no manual solver edit could be applied; the saved sequence is not hand-edited")

    def trusted_code_tool(self) -> str | None:
        """Return a *published* trusted-code tool name, or ``None``.

        The name is read off the live session inventory, never invented: this
        build publishes 65 tools and none of them executes Java, so the honest
        answer here is ``None`` (recorded as ``skipped``), not a guessed tool id.
        """
        names = sorted(getattr(self.host, "tools", {}) or {})
        matches = [name for name in names
                   if any(hint in name.lower() for hint in TRUSTED_CODE_HINTS)
                   or ("code" in name.lower() and ("execute" in name.lower() or "java" in name.lower()))]
        return matches[0] if matches else None

    async def attempt_derived_values(self) -> None:
        driver, args = self.driver, self.args
        inventory = await self.action("node.find", {
            "query": {}, "root": {"segments": []}, "limit": 500,
            "budget": {"max_nodes": 5000, "max_seconds": 30.0}}, key="fixture-node-find")
        results = [dict(row) for row in driver._data(inventory).get("results", []) if isinstance(row, Mapping)]
        numerical = [row for row in results
                     if any(str(segment.get("collection")) == "numerical"
                            for segment in (row.get("path", {}) or {}).get("segments", [])
                            if isinstance(segment, Mapping))]
        tool = self.trusted_code_tool()
        observation = {
            "numerical_nodes_observed": [{"tag": row.get("tag"), "type_id": row.get("type_id")}
                                         for row in numerical],
            "model_nodes_visited": driver._data(inventory).get("visited"),
            "trusted_code_tool": tool,
            "published_tool_count": len(getattr(self.host, "tools", {}) or {}),
        }
        self.derived_values = {"mode": "skipped",
                               "reason": "--with-derived-value was not passed",
                               "requested": False, **observation}
        if not args.with_derived_value:
            self.record("derived_values", "code execution", None, status="SKIPPED",
                        notes="--with-derived-value was not passed; no Derived Values node is claimed",
                        extra={"numerical_nodes_observed": observation["numerical_nodes_observed"]})
            return
        self.derived_values["requested"] = True
        if tool is None:
            reason = ("no trusted-code operation is published in this tool profile "
                      f"({observation['published_tool_count']} tools listed; looked for "
                      f"{', '.join(TRUSTED_CODE_HINTS)}); a Derived Values node would have to be "
                      "created outside the published surface, which this fixture never does")
            self.derived_values = {**self.derived_values, "mode": "skipped", "reason": reason}
            self.warn(f"derived values: {reason}")
            self.record("derived_values", "code execution", None, status="SKIPPED", notes=reason,
                        extra={"trusted_code_tool": None})
            return
        source = ROOT / DERIVED_VALUE_SOURCE
        if not source.is_file():
            reason = f"the Java source {DERIVED_VALUE_SOURCE} is missing"
            self.derived_values = {**self.derived_values, "mode": "skipped", "reason": reason}
            self.record("derived_values", tool, None, status="SKIPPED", notes=reason)
            return
        payload = await self.action(tool, {
            "source_artifact": DERIVED_VALUE_SOURCE, "entrypoint": DERIVED_VALUE_ENTRYPOINT,
            "arguments": {"preferred_tag": "cder1", "expression": "T"}, "mode": "trusted",
            "invariants": []}, key="fixture-derived-value")
        data = driver._data(payload)
        if driver._success(payload):
            created = data.get("readback", {}).get("created") if isinstance(data.get("readback"), Mapping) else None
            self.derived_values = {"mode": "java", "tool": tool, "source_artifact": DERIVED_VALUE_SOURCE,
                                   "entrypoint": DERIVED_VALUE_ENTRYPOINT,
                                   "created": driver._json_safe(created),
                                   "result": driver._json_safe(data.get("readback") or data),
                                   "requested": True, **observation}
            self.record("derived_values", tool, payload,
                        notes="trusted Java created the Derived Values node; the created tag is the engine's own readback")
        else:
            reason = (f"{tool} returned {driver._error_code(payload) or 'an invalid envelope'}: "
                      f"{driver._error_message(payload) or 'no message'}")
            after = await self.action("node.find", {
                "query": {}, "root": {"segments": []}, "limit": 500,
                "budget": {"max_nodes": 5000, "max_seconds": 30.0}}, key="fixture-node-find-after")
            after_rows = [dict(row) for row in driver._data(after).get("results", []) if isinstance(row, Mapping)]
            numerical = [{"tag": row.get("tag"), "type_id": row.get("type_id")} for row in after_rows
                         if any(str(segment.get("collection")) == "numerical"
                                for segment in (row.get("path", {}) or {}).get("segments", [])
                                if isinstance(segment, Mapping))]
            self.derived_values = {"mode": "skipped", "reason": reason, "requested": True,
                                   "tool": tool,
                                   "numerical_nodes_observed": numerical}
            self.warn(f"derived values: {reason}")
            self.record("derived_values", tool, payload, status="SKIPPED",
                        notes=f"{reason}; no Derived Values node is claimed",
                        extra={"numerical_nodes_observed": numerical})

    async def verify(self) -> None:
        """Read the live model back: the structure chain C depends on must be present."""
        driver = self.driver
        checks: dict[str, Any] = {}

        study = await self.action("study.inspect", {"path": self.study_path}, key="fixture-verify-study")
        study_data = driver._data(study)
        steps = self.collect_tree(study_data)
        checks["study"] = {"success": driver._success(study), "tag": self.args.study_tag,
                           "steps": [{"tag": row.get("tag"), "type_id": row.get("type_id")} for row in steps],
                           "target_step_present": any(str(row.get("tag")) == self.args.step_tag for row in steps)}
        self.record("verify", "study.inspect", study,
                    extra={"target_step_present": checks["study"]["target_step_present"]})

        tlist = await self.action("node.property_get", {"path": self.study_step_path, "names": ["tlist"]},
                                  key="fixture-verify-tlist")
        checks["tlist"] = driver._json_safe(driver._data(tlist))
        self.record("verify", "node.property_get", tlist, extra={"property": "tlist"})

        solvers = await self.action("solver.list", {"filter": {"study": self.args.study_tag}},
                                    key="fixture-verify-solvers")
        checks["solvers"] = [{"solver": row.get("solver"), "study": row.get("study"),
                              "feature_count": row.get("feature_count")}
                             for row in driver._data(solvers).get("solvers", []) if isinstance(row, Mapping)]
        self.record("verify", "solver.list", solvers)

        physics = await self.action("physics.list", {"component": self.args.component}, key="fixture-verify-physics")
        checks["physics"] = driver._json_safe(driver._data(physics))
        self.record("verify", "physics.list", physics)

        materials = await self.action("material.list", {"component": self.args.component}, key="fixture-verify-materials")
        checks["materials"] = driver._json_safe(driver._data(materials))
        self.record("verify", "material.list", materials)

        self.verification = checks
        required = [checks["study"].get("success"), checks["study"].get("target_step_present"),
                    bool(checks["solvers"]), driver._success(tlist)]
        if not all(required):
            self.warn("post-save verification did not observe the full required structure; see verification in the receipt")

    def status(self) -> int:
        required = {"model_create", "component_create", "geometry_create", "geometry_build",
                    "material_target", "physics_create", "mesh_create", "mesh_build",
                    "study_create", "study_step_transient", "study_step_tlist",
                    "study_solver_generate", "model_save"}
        failed = [row for row in self.steps if row["step"] in required and not row["success"]]
        blocked = [row for row in self.steps if row["status"] == "BLOCKED"]
        if blocked:
            return 3
        if failed:
            return 1
        if not self.solver_edit.get("applied") and not self.args.allow_no_manual_solver:
            return 1
        return 0

    # -- receipt ----------------------------------------------------------

    def receipt(self, *, exit_code: int, startup_error: str | None) -> dict[str, Any]:
        driver = self.driver
        return {
            "kind": "phase4-chain-c-user-style-fixture",
            "generated_at": _utc_now(),
            "exit_code": exit_code,
            "startup_error": startup_error,
            "label": self.args.label,
            "constraints": {
                "study_tag": self.args.study_tag,
                "step_tag": self.args.step_tag,
                "chain_c_requires": {"study_tag": REQUIRED_STUDY_TAG, "step_tag": REQUIRED_STEP_TAG},
                "satisfied": (self.args.study_tag == REQUIRED_STUDY_TAG
                              and self.args.step_tag == REQUIRED_STEP_TAG),
            },
            "sources": driver._hash_sources([DRIVER_PATH, Path(__file__).resolve(),
                                             ROOT / DERIVED_VALUE_SOURCE]),
            "environment": self.environment,
            "session": {
                "initialize": self.host.initialize_summary() if self.host is not None else None,
                "tool_count": len(getattr(self.host, "tools", {}) or {}),
                "has_operation_call": "operation_call" in (getattr(self.host, "tools", {}) or {}),
                "has_legacy_model_create": "model_create" in (getattr(self.host, "tools", {}) or {}),
                "isolation_receipt_present": bool(getattr(self.host, "isolation_receipt_present", False)),
            },
            "model_ref": driver._json_safe(self.state.get("ref")),
            "model_revision": self.state.get("revision"),
            "ops_used": sorted({row["operation"] for row in self.steps}),
            "steps": self.steps,
            "tlist": self.tlist,
            "manual_solver_edit": self.solver_edit,
            "derived_values": self.derived_values,
            "verification": self.verification,
            "warnings": self.warnings,
            "mph": {"path": str(self.output), "exists": self.output.is_file(),
                    "sha256": driver._sha256(self.output) if self.output.is_file() else None,
                    "bytes": self.output.stat().st_size if self.output.is_file() else None},
            "reopen_command": f"tools/phase4_run_mcp.py --reopen-check {self.output}",
            "continuation_command": (f"tools/phase4_run_mcp.py --live --chain-c-model {self.output} "
                                     f"--only W16_T019_chainC_continue --run-dir <run-dir>"),
            "unverified": [
                "the .mph is written and hashed, but the fixture does not reopen it: "
                "use tools/phase4_run_mcp.py --reopen-check to verify loadability in a fresh child",
                "derived values are created only through the trusted-code route; without --with-derived-value "
                "(or when the route is refused) the model has no Derived Values node and the receipt says so",
                "the chain C case itself addresses the continuation target as "
                "[{study,std1},{step,time}] with a row-list `properties`; the published operation layer "
                "rejects both forms (INVALID_NODE_PATH: unsupported path collection 'step'; "
                "INVALID_REQUEST: properties must be an object). The target this fixture prepares is "
                "writable with the verified shape -- [{study,std1},{feature,time}] plus a name->value "
                "mapping -- as replayed offline against the repository's fake node tree "
                "(tests/test_g3_chain_c_fixture.py::test_chain_c_fixture_tlist_write_works_on_the_repo_fake_tree).",
            ],
        }

    async def run(self, *, handshake_only: bool = False) -> int:
        driver, driver_args = self.driver, self.driver_args
        self.run_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
        self.environment = {
            "python": str(driver_args.python),
            "host": str(driver_args.host),
            "port": int(driver_args.port),
            "comsol_root": str(driver_args.comsol_root) if driver_args.comsol_root else None,
            "jdk11": str(driver_args.jdk11) if driver_args.jdk11 else None,
            "prefs": str(driver_args.prefs) if driver_args.prefs else None,
            "tool_profile": driver_args.tool_profile,
            "private_home": str(driver_args.private_home) if driver_args.private_home else None,
            "run_dir": str(self.run_dir),
            "output": str(self.output),
            "started_at": _utc_now(),
            "isolation_receipt_present": bool(os.environ.get("COMSOL_MCP_ISOLATION_RECEIPT")),
            "comsol_lifecycle": "not managed by this script (no COMSOL start/stop)",
        }
        exit_code = 3
        startup_error: str | None = None
        host = driver.ProductionHost(driver_args, self.run_dir, self.transcript, label="primary")
        self.host = host
        started = time.monotonic()
        try:
            async with host:
                self.environment["tool_count"] = len(host.tools)
                print(f"  .. stdio session ready: {len(host.tools)} tools, "
                      f"private home {host.private_home}")
                if handshake_only:
                    self.record("handshake", "initialize + tools/list", {"success": True},
                                status="APPLIED", extra={"initialize": host.initialize_summary()})
                    exit_code = 0
                else:
                    client = driver.ActionClient(host, driver_args, self.state)
                    try:
                        exit_code = await self.build(host, client)
                    except FixtureBlocked as exc:
                        # Handled inside the session block so the stdio child is
                        # torn down cleanly instead of through an exception group.
                        startup_error = f"blocked: {exc}"
                        exit_code = 3
                        self.record("fixture", "blocked capability", None, status="BLOCKED",
                                    notes=startup_error)
        except FixtureBlocked as exc:
            startup_error = f"blocked: {exc}"
            exit_code = 3
            self.record("session", "stdio session", None, status="BLOCKED", notes=startup_error)
        except BaseException as exc:  # noqa: BLE001 - the receipt records any driver-side failure
            startup_error = f"{type(exc).__name__}: {exc}"
            exit_code = 1
            self.record("session", "stdio session", None, status="FAILED", notes=startup_error)
        finally:
            elapsed = round(time.monotonic() - started, 3)
            self.environment["elapsed_s"] = elapsed
            self.environment["self_test"] = self_consistency()
            self._write_evidence(exit_code, startup_error)
        return exit_code

    def _write_evidence(self, exit_code: int, startup_error: str | None) -> None:
        driver = self.driver
        driver._write_json(self.run_dir / "transcript.json", {
            "transport": "stdio", "host": "primary", "call_count": len(self.transcript),
            "transcript": self.transcript})
        driver._write_json(self.receipt_path, self.receipt(exit_code=exit_code, startup_error=startup_error))
        driver._write_json(self.run_dir / "environment.json", self.environment)
        sums = []
        for path in sorted(self.run_dir.glob("*")):
            if path.is_file():
                sums.append({"path": path.name, "bytes": path.stat().st_size, "sha256": driver._sha256(path)})
        driver._write_json(self.run_dir / "SHA256SUMS.json", {"files": sums})
        print(f"  .. receipt: {self.receipt_path}")


def self_consistency() -> dict[str, Any]:
    """A cheap, offline self-check that the required tags and plan are what chain C expects."""
    steps = {item["step"] for item in PLAN_STEPS}
    required = {"study_step_transient", "study_step_tlist", "manual_solver_edit", "model_save"}
    return {"study_tag": REQUIRED_STUDY_TAG, "step_tag": REQUIRED_STEP_TAG,
            "plan_steps": len(PLAN_STEPS), "missing_plan_steps": sorted(required - steps),
            "ok": not (required - steps)}


def driver_arguments(args: argparse.Namespace) -> argparse.Namespace:
    """Translate this script's CLI into the driver's own Namespace (same env conventions)."""
    translator = load_driver().build_parser()
    argv = ["--python", str(args.python), "--host", str(args.host), "--port", str(args.port),
            "--project-id", str(args.project_id), "--tool-profile", str(args.tool_profile),
            "--run-dir", str(Path(args.run_dir).expanduser())]
    if args.comsol_root:
        argv += ["--comsol-root", str(args.comsol_root)]
    if args.jdk11:
        argv += ["--jdk11", str(args.jdk11)]
    if args.prefs:
        argv += ["--prefs", str(args.prefs)]
    if args.private_home:
        argv += ["--private-home", str(Path(args.private_home).expanduser())]
    if args.live:
        argv += ["--live"]
    return translator.parse_args(argv)


def default_run_dir() -> Path:
    return ROOT / "evidence" / "phase4" / "chain_c_fixture" / _stamp()


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(list(argv) if argv is not None else None)
    validate(args, parser)
    if args.dry_run:
        print_plan(args)
        print("dry run: no COMSOL Server, no MCP session, no files")
        return 0
    if args.run_dir is None:
        args.run_dir = str(default_run_dir())
    if args.output is None:
        args.output = Path(args.run_dir).expanduser() / "chain_c_user_style.mph"
    try:
        driver = load_driver()
    except FixtureError as exc:
        print(f"error: {exc}")
        return 2
    driver_args = driver_arguments(args)
    if not driver_args.live and not args.handshake_only:
        print("error: --live is required to build the fixture (or use --handshake-only / --dry-run)")
        return 2
    fixture = ChainCFixture(args, driver, driver_args)
    print(f"phase4 chain C fixture -> {fixture.run_dir}")
    try:
        code = asyncio.run(fixture.run(handshake_only=args.handshake_only))
    except KeyboardInterrupt:
        return 130
    print(f"exit code {code}")
    return code


if __name__ == "__main__":
    sys.exit(main())
